[package]
name = "ch_03_common_concepts"
version = "0.5.0"
authors = ["Kamran Jabbar <kamranajabbar@gmail.com>"]
edition = "2018"
repository = "https://github.com/rust-lang/cargo"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

